name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: budget_management
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 5s --health-timeout 5s --health-retries 10

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1" --health-interval 5s --health-timeout 5s --health-retries 10

    env:
      SECRET_KEY: dummy
      DEBUG: 'False'
      DB_NAME: budget_management
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: localhost
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://localhost:6379/0
      CELERY_RESULT_BACKEND: redis://localhost:6379/0

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true

      - name: Django system check
        run: python manage.py check

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run Django tests
        run: python manage.py test --verbosity 2

      - name: Type check (mypy)
        run: mypy .
